### PR TITLE
1. main.py => Discarded own changes and checked out origin/master file 

### PR DESCRIPTION
**Pull request by Saurabhm987**

### CODE REVIEW

**Comment by Saurabhm987** [comment]
While committing files, I wanted to leave separate commit message but unfortunately, It didn't work. Hence, I am commenting commit message here instead. 

**main.py**
- Checked out the latest main.py file from origin/master

**deleteMeal.js**
- Checked out the latest deleteMeal.js file from origin/master 

**favMeal.js**
- Modified current origin/master favMeal.js file. Little modification in  the route to match the favMeal route from main.py

**kitchen.html**
- This the file that I am working on. The changes made here are, New background, New Meal Card layout, hover effect( which I am supposed to modify later), Fav meal button. 

**New Images** 
- Trash Icon and Edit Icon images are added. 

Let me know If you find something irrelevant.

**Comment by Saurabhm987** [comment]
There are some conflicting files. I would like to know If I can go ahead and resolve those changes?

**Comment by pkmgarcia** [comment]
Hey @Saurabhm987, if you want to try to resolve the conflicts, I'd say go for it so you can have some experience figuring out how to resolve those. Otherwise, I can do it later tonight.

It should be okay for you to try to do it since the merge resolution will happen on feature/Frontend-New-UI-Update, and I should be able to check out what changes you made.

Just to get you started if you haven't already looked into it:

0. Make sure you have the latest version of the master branch
`git checkout master`
`git pull`

1. Go to your branch, then merge it with master
`git checkout feature/Frontend-New-UI-Update`
`git merge master`

2. Resolve the merge conflicts. At this point, the git cmd tool will tell you there are merge conflicts. There are various tools that can help you out (including one that's built into `git`, but I don't recommend using it unless you like using ViM). You can also just manually do it in your favorite text editor, so long as you understand how the merge conflict is annotated.

3. After resolving all conflicts, push the merge back to the feature/Frontend-New-UI-Update.
`git push`

After all these steps, #15 should show that there are no conflicts and the branch can be merged into master.

**Comment by pkmgarcia** [comment]
@Saurabhm987 just wanted to let you know in case you decide to try to resolve the merge conflicts: I'll resolve it if it already hasn't been later tonight, around 9 PM. I'll have it merged into master by 10 PM.

**Comment by Saurabhm987** [comment]
> Hey @Saurabhm987, if you want to try to resolve the conflicts, I'd say go for it so you can have some experience figuring out how to resolve those. Otherwise, I can do it later tonight.
> 
> It should be okay for you to try to do it since the merge resolution will happen on feature/Frontend-New-UI-Update, and I should be able to check out what changes you made.
> 
> Just to get you started if you haven't already looked into it:
> 
> 1. Make sure you have the latest version of the master branch
>    `git checkout master`
>    `git pull`
> 2. Go to your branch, then merge it with master
>    `git checkout feature/Frontend-New-UI-Update`
>    `git merge master`
> 3. Resolve the merge conflicts. At this point, the git cmd tool will tell you there are merge conflicts. There are various tools that can help you out (including one that's built into `git`, but I don't recommend using it unless you like using ViM). You can also just manually do it in your favorite text editor, so long as you understand how the merge conflict is annotated.
> 4. After resolving all conflicts, push the merge back to the feature/Frontend-New-UI-Update.
>    `git push`
> 
> After all these steps, #15 should show that there are no conflicts and the branch can be merged into master.

That's very helpful. I have gone ahead and resolved conflicts. Thanks!

**Comment by Saurabhm987** [comment]
> @Saurabhm987 just wanted to let you know in case you decide to try to resolve the merge conflicts: I'll resolve it if it already hasn't been later tonight, around 9 PM. I'll have it merged into master by 10 PM.

Resolved conflicts. If there is anything I am missing let me know.

**Pull request merged**
