### PR TITLE
Feature/frontend update

### PR DESCRIPTION
**Pull request by Saurabhm987**
I have added a partial new design. There will be some changes in the current UI. However, I would like to know If there any functionalities that I am missing.

### CODE REVIEW

**Comment by pmarathay** [comment]
Looks good to me.  How do we catch this up to master?  It looks like it is two revs behind.  Thanks,  Prashant

**Review by pmarathay — APPROVED** [review]
Looks good.  Who will merge this with Master?

**Comment by Saurabhm987** [comment]
> Looks good. Who will merge this with Master?

I think we will have to figure it out. In these new changes, I am troubling with edit meal photo. Somehow it's not working. I will get it done ASAP.

**Review by pkmgarcia — APPROVED** [review]
This is a good start! I'm seeing there are some issues with navigating to the newer home page, but otherwise seems to be okay.

**Comment by Saurabhm987** [comment]
> This is a good start! I'm seeing there are some issues with navigating to the newer home page, but otherwise seems to be okay.

Yeah. In a new home page, the background image is inherited from meal.html page. I am going to remove it soon.

**Comment by Saurabhm987** [comment]
The "upload new image" button was not working earlier. I have fixed the issue and committed new changed to the feature branch. Please have a look at it.

**Comment by pmarathay** [comment]
Approved.  Just checked out edit image buttons and everything seems to work.  Logout/Login page links work as well.  Nice job - PM

**Pull request merged**
